### ISSUE TITLE
JWT Test Failing

### ISSUE THREAD

**Issue by rickspencer3** [rickspencer3/shoots#38]
======================================================================
ERROR: setUpClass (jwt_test.JWTTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rickspencer/shoots/tests/base_test.py", line 26, in setUpClass
    cls.server = cls._set_up_server(cls)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rickspencer/shoots/tests/jwt_test.py", line 13, in _set_up_server
    server = ShootsServer(self.location,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rickspencer/shoots/shoots/shoots_server.py", line 58, in __init__
    print(self.generate_admin_jwt())
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rickspencer/shoots/shoots/shoots_server.py", line 83, in generate_admin_jwt
    return jwt.encode(payload, self.secret, algorithm='HS256')
           ^^^^^^^^^^
AttributeError: module 'jwt' has no attribute 'encode'

**Comment by rickspencer3** [comment]
The problem was python dependencies, listed here:

https://stackoverflow.com/questions/33198428/jwt-module-object-has-no-attribute-encode

**Comment by rickspencer3** [comment]
after applying the fix, the code works fine
